apiVersion: v1
kind: Secret
metadata:
  name: grafana-smtp-secret
  namespace: monitoring
type: Opaque
data:
  # 아래 값들을 실제 이메일과 앱 비밀번호로 수정하세요.
  user: YWhhZTkxQGdtYWlsLmNvbQ==
  password: anFzcCBhanJyIHd4c20gY3dpcg==
