services:
  mysql:
    image: mysql:8.0
    container_name: shopping-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopping
      MYSQL_USER: yongsu
      MYSQL_PASSWORD: password # Parameter Store의 패스워드와 일치해야 합니다.
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  admin-api:
    image: yongsuchang/shopping-admin-api:test
    container_name: admin-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopping?serverTimezone=UTC&characterEncoding=UTF-8
      # SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: password
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  shop-api:
    image: yongsuchang/shopping-shop-api:test
    container_name: shop-api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shopping?serverTimezone=UTC&characterEncoding=UTF-8
      # SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: password
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./responsive-react-app
      dockerfile: Dockerfile
  frontend:
    image: yongsuchang/shopping-frontend:test
    container_name: shopping-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - shop-api
      - admin-api

volumes:
  mysql_data: