services:
  mysql-test:
    image: mysql:8.0
    container_name: shopping-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopping
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  admin-api-test:
    image: yongsuchang/shopping-admin-api:test
    container_name: admin-api-test
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test:3306/shopping?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8081:8081"
    depends_on:
      mysql-test:
        condition: service_healthy

  shop-api-test:
    image: yongsuchang/shopping-shop-api:test
    container_name: shop-api-test
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-test:3306/shopping?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8082:8082"
    depends_on:
      mysql-test:
        condition: service_healthy

  frontend-test:
    image: yongsuchang/shopping-frontend:test
    container_name: frontend-test
    ports:
      - "80:80"
    depends_on:
      - shop-api-test
      - admin-api-test
