apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: shopping-db
data:
  my.cnf: |
    [mysqld]
    # Server ID must be unique (Master should be 1)
    server-id=2
    
    # Replication Settings
    relay-log=relay-bin
    log-bin=mysql-bin
    binlog_format=ROW
    
    # Connectivity
    bind-address=0.0.0.0


CHANGE MASTER TO
  MASTER_HOST='172.100.100.8',
  MASTER_USER='repl_user',
  MASTER_PASSWORD='repl12345',
  MASTER_LOG_FILE='mysql-bin.000031',
  MASTER_LOG_POS=1281,
  GET_MASTER_PUBLIC_KEY=1;
