# Backend Namespace AWS Secret
apiVersion: v1
kind: Secret
metadata:
  name: aws-param-store-secret
  namespace: shopping-backend
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"
  AWS_REGION: "ap-northeast-2"
---
# Admin Namespace AWS Secret
apiVersion: v1
kind: Secret
metadata:
  name: aws-param-store-secret
  namespace: shopping-admin
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"
  AWS_REGION: "ap-northeast-2"