apiVersion: v1
kind: Secret
metadata:
  name: aws-param-store-secret
  namespace: shopping-backend
type: Opaque
stringData:
  # 아래 값들을 실제 AWS 인증 정보로 변경하세요.
  AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"
  AWS_REGION: "ap-northeast-2"
