# DB Namespace Secret
apiVersion: v1
kind: Secret
metadata:
  name: shopping-secrets
  namespace: shopping-db
type: Opaque
stringData:
  mysql-root-password: "password"
  jwt-secret: "your_jwt_secret_key_value_must_be_very_long_and_secure"
---
# Backend Namespace Secret
apiVersion: v1
kind: Secret
metadata:
  name: shopping-secrets
  namespace: shopping-backend
type: Opaque
stringData:
  mysql-root-password: "password"
  jwt-secret: "your_jwt_secret_key_value_must_be_very_long_and_secure"
---
# Admin Namespace Secret
apiVersion: v1
kind: Secret
metadata:
  name: shopping-secrets
  namespace: shopping-admin
type: Opaque
stringData:
  mysql-root-password: "password"
  jwt-secret: "your_jwt_secret_key_value_must_be_very_long_and_secure"