apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api
  namespace: shopping-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-api
  template:
    metadata:
      labels:
        app: shop-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
      - name: shop-api
        image: yongsuchang/shopping-shop-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "prometheus,health"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-master-service.shopping-db.svc.cluster.local:3306/shopping_db?createDatabaseIfNotExist=true"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: shopping-secrets
              key: jwt-secret
        # AWS Parameter Store Configuration
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-param-store-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-param-store-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-param-store-secret
              key: AWS_REGION
        volumeMounts:
        - name: image-storage
          mountPath: /app/uploads/images
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shop-api-service
  namespace: shopping-backend
spec:
  selector:
    app: shop-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP