apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api
  namespace: shopping-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-api
  template:
    metadata:
      labels:
        app: shop-api
    spec:
      containers:
      - name: shop-api
        image: yongsuchang/shopping-shop-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service.shopping-db:3306/shopping_shop?createDatabaseIfNotExist=true"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: shopping-secrets
              key: jwt-secret
        # AWS Parameter Store Configuration
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-param-store-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-param-store-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-param-store-secret
              key: AWS_REGION
        volumeMounts:
        - name: image-storage
          mountPath: /app/uploads/images
      volumes:
      - name: image-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shop-api-service
  namespace: shopping-backend
spec:
  selector:
    app: shop-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
