apiVersion: v1
kind: Namespace
metadata:
  name: shopping-frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: shopping-backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: shopping-admin
---
apiVersion: v1
kind: Namespace
metadata:
  name: shopping-db
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
