apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/DATA/images
    server: storage.mall.internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: shopping-backend
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/DATA/mysql-slave
    server: storage.mall.internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: shopping-db
spec:
  storageClassName: mysql-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
# Loki Storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-loki-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-loki
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/DATA/logs/loki
    server: storage.mall.internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  storageClassName: nfs-loki
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Grafana Storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-grafana-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-grafana
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/DATA/logs/grafana
    server: storage.mall.internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: nfs-grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# Prometheus Storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-prometheus-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-prometheus
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/DATA/logs/prometheus
    server: storage.mall.internal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  storageClassName: nfs-prometheus
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi