apiVersion: v1
kind: Namespace
metadata:
  name: shopping-mall
---
apiVersion: v1
kind: Secret
metadata:
  name: shopping-secrets
  namespace: shopping-mall
type: Opaque
stringData:
  mysql-root-password: "password"
  jwt-secret: "v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-config
  namespace: shopping-mall
data:
  MYSQL_HOST: "mysql-service"
  ADMIN_DB: "shopping_admin"
  SHOP_DB: "shopping_shop"
