spring:
  application:
    name: shop-api
  profiles:
    active: dev
  config:
    import: "aws-parameterstore:/config/shopping/"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: classpath*:common-messages,classpath*:shop-messages
    encoding: UTF-8

server:
  port: 8082

upload:
  path: /app/uploads/images
 
jwt:
  secret: ${jwt.secret}
  expiration: 86400000 # 24 hours
cors:
  allowed-origins: "http://localhost,http://localhost:80,http://localhost:5173,http://127.0.0.1:5173"
